apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc-frontend
  namespace: calc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calc-frontend
  template:
    metadata:
      labels:
        app: calc-frontend
    spec:
      containers:
        - name: calc-frontend
          image: your-dockerhub-user/frontend:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: calc-frontend
  namespace: calc
spec:
  type: NodePort
  selector:
    app: calc-frontend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
